config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portafolios, except: [:show]

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'react-items', to: 'portafolios#react'
  get 'portafolio/:id', to: 'portafolios#show', as: 'portafolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end
end

app/models/portafolio.rb
class Portafolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.react
    where(subtitle: "React")
  end

  scope :ruby_on_rails_portafolio_items, -> { where(subtitle: "Ruby") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portafolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
  DevcampViewHtmlgenerator::Renderer.copyright('Myname', 'MyMsg')
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout 'blog'

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title = 'Blogs'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = Blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog = Blog.friendly.find(params[:id])
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Status changed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
require 'ostruct'
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new(name: "Guest User",
                   first_name: "Guest",
                   last_name: "User",
                   email: "guest@guest.com"
                  )
  end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_page_defaults
  end

  def set_page_defaults
    @page_title = "Devcamp Partafolio | My Portfolio Website"
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/portafolios_controller.rb
class PortafoliosController < ApplicationController
  layout 'portafolio'

  def index
    @portafolio_items = Portafolio.all
  end

  def react
    @portafolio_items = Portafolio.react
  end

  def new
    @portafolio_item = Portafolio.new
    3.times { @portafolio_item.technologies.build }
  end

  def create
    @portafolio_item = Portafolio.new(portofolio_params)

    respond_to do |format|
      if @portafolio_item.save
        format.html { redirect_to portafolios_path, notice: 'Portafolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portafolio_item = Portafolio.find(params[:id])
  end

  def update
    @portafolio_item = Portafolio.find(params[:id])
    respond_to do |format|
      if @portafolio_item.update(portofolio_params)
        format.html { redirect_to portafolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portafolio_item = Portafolio.find(params[:id])
  end

  def destroy
    @portafolio_item = Portafolio.find(params[:id])

    @portafolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portafolio_url, notice: 'Portfolio item was successfully destroyed.' }
    end
  end

  private

  def portofolio_params
    params.require(:portafolio).permit(:title,
                                       :subtitle,
                                       :body,
                                       :image,
                                       technologies_attributes: [:name])
  end
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user.is_a?(User)
      link_to 'Logout', destroy_user_session_path, method: :delete
    else
      (link_to 'Login', new_user_session_path) +
        "<br>".html_safe +
      (link_to 'Register', new_user_registration_path)
    end
  end

  def source_helper(layout)
    if session[:source]
      content_tag(:p, "Your session is #{session[:source]} on the layout #{layout}")
    end
  end

  def copyright_generator_helper
    DevcampViewHtmlgenerator::Renderer.copyright('Myname', 'MyMsg')
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portafolio_helper.rb
module PortafolioHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.title.upcase %></td>
  <td><%= blog.body %></td>
  <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/portafolios/_form.html.erb
<%= form_for(@portafolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portafolios/_portafolio_item.html.erb
<p><%= link_to portafolio_item.title, portafolio_show_path(portafolio_item)%></p>
<p><%= portafolio_item.subtitle %></p>
<p><%= portafolio_item.body %></p>
<%= image_tag portafolio_item.thumb_image unless portafolio_item.thumb_image.nil? %>
<%= link_to 'edit', edit_portafolio_path(portafolio_item.id) %>
<%= link_to 'Delete Portafolio Item', portafolios_path, method: :delete, data: { confirm: 'Are you sure?' }  %>

app/views/portafolios/edit.html.erb
<h1>Edit this Portafolio Item</h1>

<%= render 'form', portafolio_item: @portafolio_item %>

app/views/portafolios/index.html.erb
<h3>Portafolio Items</h3>

<!-- <a href=>Create New Item</a> -->

<%= link_to 'Create New Item', new_portafolio_url %>

<%= render partial: 'portafolio_item', collection: @portafolio_items %>

app/views/portafolios/new.html.erb
<h1>Create a new Portafolio Item</h1>

<%= render 'form', portafolio_item: @portafolio_item %>

app/views/portafolios/react.html.erb
<h1>React Portafolio Items</h1>

<!-- <a href=>Create New Item</a> -->

<%= link_to 'Create New Item', new_portafolio_url %>

<% @portafolio_items.each do |portafolio_item| %>
  <p><%= link_to portafolio_item.title, portafolio_show_path(portafolio_item)%></p>
  <p><%= portafolio_item.subtitle %></p>
  <p><%= portafolio_item.body %></p>
  <%= image_tag portafolio_item.thumb_image unless portafolio_item.thumb_image.nil? %>
  <%# <%= link_to 'edit', edit_portafolio_path(portafolio_item.id) %>
  <%= link_to 'Delete Portafolio Item', portafolios_path, method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>

app/views/portafolios/show.html.erb
<h1>Show</h1>

<%= image_tag @portafolio_item.main_image unless @portafolio_item.main_image.nil? %>
<em> <%= @portafolio_item.title %> </em>
<em> <%= @portafolio_item.subtitle %> </em>
<em> <%= @portafolio_item.body %> </em>

<h2>Technologies Used:</h2>

<% @portafolio_item.technologies.each do |t| %>
  <p> <%= t.name %> </p>
<% end %>