config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portafolios, except: [:show]

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'react-items', to: 'portafolios#react'
  get 'portafolio/:id', to: 'portafolios#show', as: 'portafolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end
end

app/models/portafolio.rb
class Portafolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.react
    where(subtitle: "React")
  end

  scope :ruby_on_rails_portafolio_items, -> { where(subtitle: "Ruby") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portafolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
  DevcampViewHtmlgenerator::Renderer.copyright('Myname', 'MyMsg')
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout 'blog'

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title = 'Blogs'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = Blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog = Blog.friendly.find(params[:id])
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Status changed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/portafolios_controller.rb
class PortafoliosController < ApplicationController
  layout 'portafolio'

  def index
    @portafolio_items = Portafolio.all
  end

  def react
    @portafolio_items = Portafolio.react
  end

  def new
    @portafolio_item = Portafolio.new
    3.times { @portafolio_item.technologies.build }
  end

  def create
    @portafolio_item = Portafolio.new(portofolio_params)

    respond_to do |format|
      if @portafolio_item.save
        format.html { redirect_to portafolios_path, notice: 'Portafolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portafolio_item = Portafolio.find(params[:id])
  end

  def update
    @portafolio_item = Portafolio.find(params[:id])
    respond_to do |format|
      if @portafolio_item.update(portofolio_params)
        format.html { redirect_to portafolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portafolio_item = Portafolio.find(params[:id])
  end

  def destroy
    @portafolio_item = Portafolio.find(params[:id])

    @portafolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portafolio_url, notice: 'Portfolio item was successfully destroyed.' }
    end
  end

  private

  def portofolio_params
    params.require(:portafolio).permit(:title,
                                       :subtitle,
                                       :body,
                                       :image,
                                       technologies_attributes: [:name])
  end
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user.is_a?(User)
      link_to 'Logout', destroy_user_session_path, method: :delete
    else
      (link_to 'Login', new_user_session_path) +
        "<br>".html_safe +
      (link_to 'Register', new_user_registration_path)
    end
  end

  def source_helper(layout)
    if session[:source]
      content_tag(:p, "Your session is #{session[:source]} on the layout #{layout}")
    end
  end

  def copyright_generator_helper
    DevcampViewHtmlgenerator::Renderer.copyright('Myname', 'MyMsg')
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portafolio_helper.rb
module PortafolioHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/nav', location: 'top' %>

    <%= login_helper %>
    <%= copyright_generator_helper %>

    <%= yield %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

    <%= render 'shared/nav', location: 'bottom' %>

    <%= source_helper("blog") %>

  </body>
</html>

app/views/layouts/portafolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'portafolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/nav', location: 'top' %>

    <% if current_user.is_a?(User) %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete%>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>


    <%= yield %>

    <%= source_helper("portafolios") %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name if current_user %> </h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/shared/_nav.html.erb
<div class='<%= location %>'>
  <div><%= link_to 'home', root_path %></div>
  <div><%= link_to 'About Me', about_path %></div>
  <div><%= link_to 'Contact', contact_path %></div>
  <div><%= link_to 'Blogs', blogs_path %></div>
  <div><%= link_to 'Portafolios', portafolios_path %></div>
</div>